### ISSUE TITLE
pyportal.get_local_time() failure, NoneType

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_PortalBase#24]
Calls to `pyportal.get_local_time(secrets["timezone"])` fail with error:

```
  File "/lib/adafruit_portalbase/__init__.py", line 403, in get_local_time
  File "/lib/adafruit_portalbase/network.py", line 233, in get_local_time
  File "/lib/adafruit_portalbase/network.py", line 216, in get_strftime
  File "/lib/adafruit_portalbase/network.py", line 202, in get_strftime
AttributeError: 'NoneType' object has no attribute 'get'
```

Printing on L198 (https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/main/adafruit_portalbase/network.py#L198):
```        try:
            print(self._wifi)
            print(dir(self._wifi))
            print(self._wifi.requests)
```

Yields a `None` type for `self._wifi.requests`.
```
Getting time for timezone Etc/UTC
<WiFi object at 20003fe0>
['__class__', '__dict__', '__init__', '__module__', '__qualname__', 'connect', 'enabled', 'requests', 'esp', 'is_connected', 'neo_status', 'manager', 'neopix', '_manager']
None
```

Example code for where this occurs: https://learn.adafruit.com/pyportal-google-calendar-event-display/code-usage

**Comment by Neradoc** [comment]
So I just encountered that on the help channel on discord, and the quick solution with that demo was to remove:
```py
print("Connecting to AP...")
while not esp.is_connected:
    try:
        esp.connect_AP(secrets["ssid"], secrets["password"])
    except RuntimeError as e:
        print("could not connect to AP, retrying: ", e)
        continue
print("Connected to", str(esp.ssid, "utf-8"), "\tRSSI:", esp.rssi)
```
and replace with this (a few lines lower)
```py
pyportal.network.connect()
```
Here: https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/5fd9a2e74dbfd6056136a79e2ca3ad645f1a7680/PyPortal_Google_Calendar/code.py#L71-L81

For me it's a problem with duplicating features when using a large *device-name* library. You can't do that with pins for example because they will be "already in use", and it shouldn't be done with the wifi connection either in these libraries. I would also advise to use `requests = pyportal.network.requests` or `PortalBase.fetch()` and similar, especially on the MagTag where you'll otherwise end up with multiple `requests.Session` (that's a different issue though).

A workaround to still allow connecting outside of the library would be to add something like this to `PyPortal.connect()`, where `setup_when_connected()` would basically be `_wifi.connect()` minus the connection part. Each board module based on PortalBase would need to be modified.
```py
    while not self._wifi.is_connected:
        [...]
    # add:
    if not self.requests:
        self._wifi.setup_after_connection()
        self.requests = self._wifi.requests
```
After the while loop:
https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/d65f1ad71e6e4242c2454aa0f43ef38864075264/adafruit_portalbase/network.py#L324

That's because that connection code that sets up `requests` is called **if and only if** the board is not currently connected to wifi, even when called from `get_local_time()`.

**Comment by colejd** [comment]
I'm still seeing this error output on the latest version of the library.
